version: '3'
services:
  web:
    image: yelp 
    networks:
      - webnet
    ports:
      - 3000:3000
    environment:
      DB_HOST: db 
    depends_on: 
      - db
    command:
      bash -c "npm run build && npm start"
  db:
    image: postgres
    volumes: 
      - pgdata:/var/lib/postgresql/data
    networks:
      - webnet
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 'pass'
      POSTGRES_USER: postgres
      POSTGRES_DB: practice
volumes:
  pgdata:
networks:
  webnet:
