const Router = require('express').Router();
const { questionsController } = require('../controllers/questionsController.js')
const { usersController } = require('../controllers/usersController.js')

Router.route('/questions/:id')
  .get(questionsController.get)
  .delete(questionsController.delete)
  Router.route('/questions')
  .put(questionsController.put)
  .post(questionsController.post)
Router.route('/answers')
  .post(questionsController.giveAnswer)
  .put(questionsController.changeAnswer)
Router.route('/getPhoto/:id')
  .get(usersController.getPhoto)
  Router.route('/getAnswers/:id')
  .get(questionsController.getAnswers)
  .delete(questionsController.deleteAnswer)
  Router.route('/users')
  .post(usersController.post)
  Router.route('/users/:username')
  .delete(usersController.delete)
  .put(usersController.put)

module.exports = {Router:Router}
